version: "3.9"
services:
  backend:
    image: 320516442231.dkr.ecr.eu-west-1.amazonaws.com/backend:${BACKEND_VERSION:-v0.0.6}
    init: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: heslojeveslo
      MYSQL_DATABASE: test
