version: "3.9"
services:
  backend:
    image: backend:dev-v0.0.1
    init: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - modules:/opt/project/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: heslojeveslo
      MYSQL_DATABASE: test

volumes:
  modules:
